.TH "D:/Projects/JSSP-QT/src/gantt/arrow.cpp" 3 "Fri Jun 15 2018" "Version iota" "JSSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Projects/JSSP-QT/src/gantt/arrow.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <QtGui>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <arrow\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUSE_MATH_DEFINES\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const qreal \fBPi\fP = M_PI"
.br
.ti -1c
.RI "const qreal \fBarrowSize\fP = 10"
.br
.in -1c
.SH "Detailed Description"
.PP 
Draw arrow\&.
.PP
\fBAuthor:\fP
.RS 4
Name1e5s 
.RE
.PP

.PP
Definition in file \fBarrow\&.cpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define USE_MATH_DEFINES"

.PP
Definition at line 10 of file arrow\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const qreal arrowSize = 10"

.PP
Definition at line 16 of file arrow\&.cpp\&.
.SS "const qreal Pi = M_PI"

.PP
Definition at line 15 of file arrow\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for JSSP Solver from the source code\&.
