.TH "include/arrow.h" 3 "Thu Jun 14 2018" "Version iota" "JSSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/arrow.h
.SH SYNOPSIS
.br
.PP
\fC#include <QGraphicsLineItem>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBArrow\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file defines how to draw an arrow on thegantt chart\&.
.PP
\fBAuthor:\fP
.RS 4
Name1e5s 
.RE
.PP

.PP
Definition in file \fBarrow\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for JSSP Solver from the source code\&.
