.TH "algorithm/common_definition.cpp" 3 "Thu Jun 14 2018" "Version iota" "JSSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
algorithm/common_definition.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <bottle\&.h>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "\fBjob_t\fP \fBjob\fP [\fBMAXJOB\fP]"
.br
.ti -1c
.RI "int \fBjob_size\fP = 1"
.br
.ti -1c
.RI "int \fBmachine_size\fP = 1"
.br
.ti -1c
.RI "int \fBterminate_flag\fP = 0"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "job"
Data representation of all the jobs\&. All operations runs on this varible\&. 
.PP
Definition at line 5 of file common_definition\&.cpp\&.
.SS "job_size = 1"
Job number in this instance\&. 
.PP
Definition at line 10 of file common_definition\&.cpp\&.
.SS "machine_size = 1"
Machine number in this instance\&. 
.PP
Definition at line 15 of file common_definition\&.cpp\&.
.SS "terminate_flag = 0"
Should we stop??? 
.PP
Definition at line 20 of file common_definition\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for JSSP Solver from the source code\&.
