.TH "D:/Projects/JSSP-QT/src/algorithm Directory Reference" 3 "Sun Jun 17 2018" "Version iota" "JSSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Projects/JSSP-QT/src/algorithm Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbottle\&.cpp\fP"
.br
.RI "Core algorithms\&. "
.ti -1c
.RI "file \fBcommon_definition\&.cpp\fP"
.br
.ti -1c
.RI "file \fBeval\&.cpp\fP"
.br
.RI "makespan "
.ti -1c
.RI "file \fBonemachine\&.cpp\fP"
.br
.RI "One-machine sequencing\&. "
.in -1c
