.TH "Fixer" 3 "Sun Jun 17 2018" "Version iota" "JSSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fixer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <jobshop\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBmachine\fP"
.br
.ti -1c
.RI "int \fBstarttime\fP"
.br
.ti -1c
.RI "int \fBduration\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file jobshop\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int Fixer::duration"

.PP
Definition at line 25 of file jobshop\&.h\&.
.SS "int Fixer::machine"

.PP
Definition at line 23 of file jobshop\&.h\&.
.SS "int Fixer::starttime"

.PP
Definition at line 24 of file jobshop\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JSSP Solver from the source code\&.
