.TH "D:/Projects/JSSP-QT/src/include/ganttchartmachine.h" 3 "Sun Jun 17 2018" "Version iota" "JSSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Projects/JSSP-QT/src/include/ganttchartmachine.h
.SH SYNOPSIS
.br
.PP
\fC#include <QGraphicsItem>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGanttChartMachine\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file defines how to present the gantt chart per machine\&.
.PP
\fBAuthor:\fP
.RS 4
Name1e5s 
.RE
.PP

.PP
Definition in file \fBganttchartmachine\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for JSSP Solver from the source code\&.
