.TH "gantt/ganttchartoperation.cpp" 3 "Thu Jun 14 2018" "Version iota" "JSSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gantt/ganttchartoperation.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <ganttchartoperation\&.h>\fP
.br
\fC#include <ganttchartbase\&.h>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QPainter>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for JSSP Solver from the source code\&.
