.TH "D:/Projects/JSSP-QT/src/include/ganttchartprogress.h" 3 "Fri Jun 15 2018" "Version iota" "JSSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Projects/JSSP-QT/src/include/ganttchartprogress.h
.SH SYNOPSIS
.br
.PP
\fC#include <QThread>\fP
.br
\fC#include <bottle\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGanttChartProgress\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBbest_makespan\fP"
.br
.RI "Store the best makespan value\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Name1e5s 
.RE
.PP

.PP
Definition in file \fBganttchartprogress\&.h\fP\&.
.SH "Variable Documentation"
.PP 
.SS "int best_makespan"

.PP
Store the best makespan value\&. 
.PP
Definition at line 47 of file bottle\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for JSSP Solver from the source code\&.
