.TH "GanttChartProgress" 3 "Fri Jun 15 2018" "Version iota" "JSSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GanttChartProgress
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ganttchartprogress\&.h>\fP
.PP
Inherits QThread\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBupdateline\fP (int n)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGanttChartProgress\fP (double in_speed=1\&.0, QObject *parent=0)"
.br
.ti -1c
.RI "void \fBsetSpeed\fP (double value)"
.br
.RI "\fBGanttChartProgress::setSpeed\fP\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBrun\fP () Q_DECL_OVERRIDE"
.br
.RI "\fBGanttChartProgress::run\fP\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "double \fBspeed\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file ganttchartprogress\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GanttChartProgress::GanttChartProgress (double in_speed = \fC1\&.0\fP, QObject * parent = \fC0\fP)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 17 of file ganttchartprogress\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void GanttChartProgress::run ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
\fBGanttChartProgress::run\fP\&. 
.PP
Definition at line 14 of file ganttchartprogress\&.cpp\&.
.SS "void GanttChartProgress::setSpeed (double value)"

.PP
\fBGanttChartProgress::setSpeed\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvalue\fP 
.RE
.PP

.PP
Definition at line 27 of file ganttchartprogress\&.cpp\&.
.SS "void GanttChartProgress::updateline (int n)\fC [signal]\fP"

.SH "Member Data Documentation"
.PP 
.SS "double GanttChartProgress::speed\fC [private]\fP"

.PP
Definition at line 25 of file ganttchartprogress\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JSSP Solver from the source code\&.
