.TH "D:/Projects/JSSP-QT/src/gantt/ganttchartbase.cpp" 3 "Fri Jun 15 2018" "Version iota" "JSSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Projects/JSSP-QT/src/gantt/ganttchartbase.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <QGraphicsLineItem>\fP
.br
\fC#include <QGraphicsScene>\fP
.br
\fC#include <QGraphicsSimpleTextItem>\fP
.br
\fC#include <QFont>\fP
.br
\fC#include <QPen>\fP
.br
\fC#include <QPainter>\fP
.br
\fC#include <QStyleOptionGraphicsItem>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <ganttchartbase\&.h>\fP
.br
\fC#include <bottle\&.h>\fP
.br

.SH "Detailed Description"
.PP 
Basic definition of our gantt chart\&.
.PP
\fBAuthor:\fP
.RS 4
Name1e5s 
.RE
.PP

.PP
Definition in file \fBganttchartbase\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for JSSP Solver from the source code\&.
