.TH "D:/Projects/JSSP-QT/src/include/ganttchartoperation.h" 3 "Sun Jun 17 2018" "Version iota" "JSSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Projects/JSSP-QT/src/include/ganttchartoperation.h
.SH SYNOPSIS
.br
.PP
\fC#include <QGraphicsRectItem>\fP
.br
\fC#include <QString>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGanttChartOperation\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file defines how to present a operation on the m=gantt chart\&.
.PP
\fBAuthor:\fP
.RS 4
Name1e5s 
.RE
.PP

.PP
Definition in file \fBganttchartoperation\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for JSSP Solver from the source code\&.
