.TH "D:/Projects/JSSP-QT/src/ui/input.cpp" 3 "Fri Jun 15 2018" "Version iota" "JSSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Projects/JSSP-QT/src/ui/input.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'ui_input\&.h'\fP
.br
\fC#include <input\&.h>\fP
.br
\fC#include <result\&.h>\fP
.br
\fC#include <jobshop\&.h>\fP
.br

.SH "Detailed Description"
.PP 
Draw input window\&.
.PP
\fBAuthor:\fP
.RS 4
Name1e5s 
.RE
.PP

.PP
Definition in file \fBinput\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for JSSP Solver from the source code\&.
