.TH "Input" 3 "Sun Jun 17 2018" "Version iota" "JSSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Input
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <input\&.h>\fP
.PP
Inherits QMainWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInput\fP (QWidget *parent=0)"
.br
.RI "Set the input window\&. "
.ti -1c
.RI "\fB~Input\fP ()"
.br
.RI "Delete the window\&. "
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "void \fBon_start_button_clicked\fP ()"
.br
.RI "Action of start button\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Ui::Input * \fBui\fP"
.br
.ti -1c
.RI "\fBJobShop\fP * \fBjssp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file input\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Input::Input (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Set the input window\&. 
.PP
\fBParameters:\fP
.RS 4
\fIparent\fP 
.RE
.PP

.PP
Definition at line 18 of file input\&.cpp\&.
.SS "Input::~Input ()"

.PP
Delete the window\&. 
.PP
Definition at line 32 of file input\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Input::on_start_button_clicked ()\fC [private]\fP, \fC [slot]\fP"

.PP
Action of start button\&. 
.PP
Definition at line 41 of file input\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBJobShop\fP* Input::jssp\fC [private]\fP"

.PP
Definition at line 32 of file input\&.h\&.
.SS "Ui::Input* Input::ui\fC [private]\fP"

.PP
Definition at line 31 of file input\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JSSP Solver from the source code\&.
