.TH "D:/Projects/JSSP-QT/src/include/jobshop.h" 3 "Sun Jun 17 2018" "Version iota" "JSSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Projects/JSSP-QT/src/include/jobshop.h
.SH SYNOPSIS
.br
.PP
\fC#include <QObject>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QVector>\fP
.br
\fC#include <ganttchartbase\&.h>\fP
.br
\fC#include <bottle\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBFixer\fP"
.br
.ti -1c
.RI "class \fBJobShop\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file is a simple wrapper for the previous CLI version of this project to make it compatible with QT\&.
.PP
!!!Note: This implementation is not a good pratice\&.
.PP
\fBAuthor:\fP
.RS 4
Name1e5s 
.RE
.PP

.PP
Definition in file \fBjobshop\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for JSSP Solver from the source code\&.
