.TH "jobshop.cpp" 3 "Thu Jun 14 2018" "Version iota" "JSSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jobshop.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <jobshop\&.h>\fP
.br
\fC#include <bottle\&.h>\fP
.br
\fC#include <ganttchartbase\&.h>\fP
.br
\fC#include <ganttchartmachine\&.h>\fP
.br
\fC#include <ganttchartoperation\&.h>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include <QTextStream>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBbest_makespan\fP"
.br
.RI "Store the best makespan value\&. "
.in -1c
.SH "Detailed Description"
.PP 
Simple wrapper of previous version of JSSP solver\&.
.PP
\fBAuthor:\fP
.RS 4
Name1e5s 
.RE
.PP

.PP
Definition in file \fBjobshop\&.cpp\fP\&.
.SH "Variable Documentation"
.PP 
.SS "int best_makespan"

.PP
Store the best makespan value\&. 
.PP
Definition at line 45 of file bottle\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for JSSP Solver from the source code\&.
