.TH "MACHINEORDER" 3 "Thu Jun 14 2018" "Version iota" "JSSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MACHINEORDER
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "int \fBmachines\fP [\fBMAXMACHINE\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Machine order type\&. 
.PP
Definition at line 28 of file bottle\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "int MACHINEORDER::machines[\fBMAXMACHINE\fP]"
Sequenced machine list\&. 
.PP
Definition at line 30 of file bottle\&.cpp\&.
.SS "int MACHINEORDER::size"
Sequenced machine number\&. 
.PP
Definition at line 29 of file bottle\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JSSP Solver from the source code\&.
