.TH "D:/Projects/JSSP-QT/src/main.cpp" 3 "Sun Jun 17 2018" "Version iota" "JSSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Projects/JSSP-QT/src/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <QApplication>\fP
.br
\fC#include <input\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int ac, char *av[])"
.br
.in -1c
.SH "Detailed Description"
.PP 
Enterpoint of the program\&.
.PP
\fBAuthor:\fP
.RS 4
Name1e5s 
.RE
.PP

.PP
Definition in file \fBmain\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int ac, char * av[])"

.PP
Definition at line 11 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for JSSP Solver from the source code\&.
