.TH "NEIGHBOR" 3 "Thu Jun 14 2018" "Version iota" "JSSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NEIGHBOR
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnext\fP [\fBMAXMACHINE\fP]"
.br
.ti -1c
.RI "int \fBprev\fP [\fBMAXMACHINE\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
A temporary struct to store a sequence\&. 
.PP
Definition at line 37 of file bottle\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "int NEIGHBOR::next[\fBMAXMACHINE\fP]"
You will be either silly or able to understand the name's mean\&. 
.PP
Definition at line 38 of file bottle\&.cpp\&.
.SS "int NEIGHBOR::prev[\fBMAXMACHINE\fP]"
Same as the previous one\&. 
.PP
Definition at line 39 of file bottle\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JSSP Solver from the source code\&.
