.TH "ONEMACHINestime" 3 "Sun Jun 17 2018" "Version iota" "JSSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ONEMACHINestime
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bottle\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBestime\fP [\fBMAXJOB\fP]"
.br
.ti -1c
.RI "int \fBmhtime\fP [\fBMAXJOB\fP]"
.br
.ti -1c
.RI "int \fBprocess_time\fP [\fBMAXJOB\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Store the time info for every job runs on the same machine\&. 
.PP
Definition at line 63 of file bottle\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int ONEMACHINestime::estime[\fBMAXJOB\fP]"
See 'JOBTYPE' for more info\&. 
.PP
Definition at line 64 of file bottle\&.h\&.
.SS "int ONEMACHINestime::mhtime[\fBMAXJOB\fP]"
See 'JOBTYPE' for more info\&. 
.PP
Definition at line 65 of file bottle\&.h\&.
.SS "int ONEMACHINestime::process_time[\fBMAXJOB\fP]"
See 'JOBTYPE' for more info\&. 
.PP
Definition at line 66 of file bottle\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JSSP Solver from the source code\&.
