.TH "ONEMACHINE_BRANCH_AND_BOUND_ASSISTANT" 3 "Sun Jun 17 2018" "Version iota" "JSSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ONEMACHINE_BRANCH_AND_BOUND_ASSISTANT
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBactive\fP"
.br
.ti -1c
.RI "int \fBbound\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Info of node of a branch and bound tree\&. 
.PP
Definition at line 22 of file onemachine\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "int ONEMACHINE_BRANCH_AND_BOUND_ASSISTANT::active"
Wether this node is active 
.PP
Definition at line 23 of file onemachine\&.cpp\&.
.SS "int ONEMACHINE_BRANCH_AND_BOUND_ASSISTANT::bound"
See 'JOBTYPE' for more info\&. 
.PP
Definition at line 24 of file onemachine\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JSSP Solver from the source code\&.
