.TH "PAIR_ASSISTANT_TYPE" 3 "Sun Jun 17 2018" "Version iota" "JSSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAIR_ASSISTANT_TYPE
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBstart_time\fP"
.br
.ti -1c
.RI "int \fBjob_num\fP"
.br
.ti -1c
.RI "int \fBmach_num\fP"
.br
.ti -1c
.RI "int \fBproc_time\fP"
.br
.ti -1c
.RI "int \fBstep\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A temporary struct for converting the internal representation of the solution to the format required by those soreheads\&. 
.PP
Definition at line 24 of file io\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "int PAIR_ASSISTANT_TYPE::job_num"
Serial number of the job of this node\&. 
.PP
Definition at line 26 of file io\&.cpp\&.
.SS "int PAIR_ASSISTANT_TYPE::mach_num"
Serial number of the machine of this node\&. 
.PP
Definition at line 27 of file io\&.cpp\&.
.SS "int PAIR_ASSISTANT_TYPE::proc_time"
Process time (a\&.k\&.a duration) of this node\&. 
.PP
Definition at line 28 of file io\&.cpp\&.
.SS "int PAIR_ASSISTANT_TYPE::start_time"
Start time of this node\&. 
.PP
Definition at line 25 of file io\&.cpp\&.
.SS "int PAIR_ASSISTANT_TYPE::step"
Serial number of the order of this node in the job\&. 
.PP
Definition at line 29 of file io\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JSSP Solver from the source code\&.
