.TH "pair" 3 "Sun Jun 17 2018" "Version iota" "JSSP Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pair \- The pair struct for sorting machines\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBstarttime\fP"
.br
.ti -1c
.RI "int \fBendtime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The pair struct for sorting machines\&. 
.PP
Definition at line 26 of file result\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "int pair::endtime"

.PP
Definition at line 29 of file result\&.cpp\&.
.SS "int pair::starttime"

.PP
Definition at line 28 of file result\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JSSP Solver from the source code\&.
